### ISSUE TITLE
CSV, NULL, and MySQL

### ISSUE THREAD

**Issue by joshuashort** [brianb/mdbtools#100]
Is there any way to change the way a null value appears in CSV? It'd be very helpful to be able to specify a placeholder.

**Comment by nirgal** [comment]
Hi

Unfortunatly, csv format does not support NULL. You'll have to use `mdb-export -I mysql ....`

**Comment by joshuashort** [comment]
I ended up digging into the code last week; there was a comment that indicated where the change could go. Instead of generating insert statements (which takes a little under an hour to import on the database I'm working with), a simple addition to mdbtools allows generating CSVs with NULL placeholders (supported by MySQL), and the same process takes about a minute.

https://github.com/brianb/mdbtools/pull/101
