### ISSUE TITLE
String Encoding Conversion

### ISSUE THREAD

**Issue by xiegeo** [brianb/mdbtools#103]
There should be a way to specify input and output encoding for mdb-export, or a flag to treat strings as raw to not mangle it further. 

Under my environment, I have to use `mdb-export datafile.mdb DB | iconv -f utf-8 -t cp1252 | iconv -f gb2312 -t utf-8`. This requires a double conversion which was not easy to figure out.

**Comment by nirgal** [comment]
Wow, this is a weird way to do things.

Are you using some old JET3 files? The file character set can be specified using MDB_JET3_CHARSET environment variable.

The output charset can be specified using MDBICONV environment variable.

Please read the manual mdb-export(1).

Do you have an issue with these?

**Comment by xiegeo** [comment]
Thank you, that worked. I only though to read the self printed usage info.
