### ISSUE TITLE
mdb-export produce many malformed utf 8 characters

### ISSUE THREAD

**Issue by caiiiycuk** [brianb/mdbtools#16]
I have mdb database (JET4), when i use mdb-viewer for produce csv file all works fine. But when i use mdb-export for convert same mdb, output csv contains a lot of malformed characters and result file almost unredable. I try to use enviroment variables for manually set charset to UTF-8 but unsucessfull.

For convertation i use command: 

```
mdb-export -d ';' something.mdb Main > Main.csv
```

Mdb viewer works perfect but i have a many databases so i need console tool.

**Comment by shakram02** [comment]
Is Arabic text supported? I get an output like this when exporting a file containing Arabic text 

```
mdb-export -d '\n' 0810 b810
```

I'm sorry that I can't share the file here

![image](https://user-images.githubusercontent.com/10996982/46247402-3c4a8080-c40b-11e8-8451-ad48b8339841.png)

**Comment by mamprogr** [comment]
I face the same issue with Arabic, is there any solution?
![image](https://user-images.githubusercontent.com/734475/235015916-3973b2a7-7ec0-4596-a682-696bedc3b13a.png)

**Comment by evanmiller** [comment]
@mamprogr Can you share the file?

**Comment by mamprogr** [comment]
Sure, https://tmpfiles.org/1348192/test.mdb

**Comment by evanmiller** [comment]
Try this

https://github.com/mdbtools/mdbtools/commit/d9025dbf22c23fd0a79929e86162e2cc4dce6e13

**Comment by evanmiller** [comment]
With the linked patch I see

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/134711/235027624-94b4e3fc-f862-4983-81df-18bc80212877.png">

**Comment by mamprogr** [comment]
This is the correct output, thanks.
How can I apply this patch in my side?
