### ISSUE TITLE
mdb-schema always outputs comments

### ISSUE THREAD

**Issue by Gregy** [brianb/mdbtools#63]
mdb-schema always outputs comments even with --no-comments.

**Comment by nirgal** [comment]
I cannot reproduce this problem. oO

Which version are you using? (One from a distro? Last version from github?)
Which backend are you using? (postgres? oracle? mysql?)
What is your OS?

**Comment by Gregy** [comment]
Sorry for the lack of details. I am using latest version from github with sqlite backend. I am running debian testing.

I am running it like this:
./mdb-schema --no-comments <file> sqlite

**Comment by nirgal** [comment]
Maybe the documentation is not clear, but comments are database comments, not SQL comments like lines starting with "-- ". And it's not supported with sqlite backend, so it's unlikely you have them.
Here's an exemple of comments with postgres:
COMMENT ON COLUMN "tAppeal"."bActual" IS 'Actual vs History';
COMMENT ON TABLE "tAppeal" IS 'Appeal List';
In access, this is called description of columns, I think.

Was it communication problem? Or do you actually get column/table comments in sqlite?

**Comment by Gregy** [comment]
Oh, I see. Well that explains it. I thought it should turn off sql comments. Thanks!

**Comment by nirgal** [comment]
I commited 13e339c1a42e996e9620e4326fdbee4d3734f55d with a more detailed explanation of what --no-comments is about, and improved man page.
Thank you for your report. Hopefully, it will helps others.
