### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by russellbstephens** [brianb/mdbtools#79]
Does mdbtools support reading from and writing to .mdb/.accdb?

**Comment by nirgal** [comment]
Hello

Yes, you can read and write. I think write has not been tested much, especially on accdb files.

If you use the low level functions, you need to add MDB_WRITABLE parameter to mdb_open.

High level functions include mdb-import tool. I'm not sure whether it's part of last release, you might have to lastest snapshot.

Please reopen the issue if you require more details.
You can impo
