### ISSUE TITLE
Birthday bonus bug in the market edit page

### ISSUE THREAD

**Issue by JacobPaul** [brianb/mdbtools#97]
There seems to be a bug with saving a birthday bonus and changing the conversion rates. When trying to make changes to both in the same save the birthday bonus doesn't get saved. Will work toward pin pointing the combination that causes the issue.

**Comment by nirgal** [comment]
wtf?

**Comment by JacobPaul** [comment]
wow not sure how this got here. I must have used the wrong link. Sorry about this.
