### ISSUE TITLE
mdb-export JET4 not working

### ISSUE THREAD

**Issue by felipensp** [brianb/mdbtools#98]
I've tried to export a sample database (http://www.arialsoftware.com/uploads/9/1/8/3/9183466/campaign_template1.zip) using the mdbtools 0.7.1, but I just got the CSV header from this file.

`$ mdb-export Campaign_Template.mdb Campaign_Table
ID,Email_Address,First_Name,Last_Name,Address,City,State,Country,Postal_Code,ProductID,Date_Added,Phone,CC_Email,Message_Sent,Bounce,Softbounce,Unsubscribe,Subscribe,Bad_Format,Date_Sent,Opened_Email,Click_1,Click_2,Click_3,Click_4,Click_5`

**Comment by nirgal** [comment]
Because that table is empty: There are no line to display. Only column names (header).
